# Comments are supported, using a #
# The default section is [default], case-insensitive

input1 = "../../delaunay-cavity-data/data/points1000000.14.node" # Mandatory, must be .node or .off
input2 = "../../delaunay-cavity-data/data/points1000000.14.ele" # Must be .ele if off-input is false, else it should be omitted
input3 = "../../delaunay-cavity-data/data/points1000000.14.neigh" # Must be .neigh if off-input is false, else it should be omitted

output = "../../delaunay-cavity-data/experiments/points1000000_70_longest_edge" # Root filename of output, appropriate extensions are appended to this name
off-output = true # true if an off output file is desired
json-output = true # true if a json file with stats is desired
ale-output = true # true  if an ale output file is desired
#off-input = true # true if an off input file will be provided on input1
#threshold = 0.9698463044600625 # A double type value whose meaning depends on the selection criterion
#seed = 123 # A number that represents a random seed, only used for the random triangle comparator
write-intermediate = true # true if an intermediate off file before post processing is done is required, only valid for a merging strategy that does post processing